### ISSUE TITLE
Request to add license to the repo

### ISSUE THREAD

**Issue by sara-02** [pythonindia/inpycon2021#65]
Hello, I want to reuse your conference template for a commercial research conference (International Conference on Natural Language Processing 2022) being held in India.
It would be great if you could add a license to the repo.

**Comment by raukadah** [comment]
https://github.com/pythonindia/inpycon2021/pull/66 fixes the same

**Comment by realslimshanky** [comment]
Closing the issue as PR has been merged and deployed.
